### ISSUE TITLE
How to use it in VUE or React

### ISSUE THREAD

**Issue by ziqiangai** [williamtroup/Heat.js#33]
There is no guidance in the documentation.

**Comment by williamtroup** [comment]
In what context?

**Comment by ziqiangai** [comment]
I introduced `heat.js` in vue to throw such an error.

<img width="592" alt="image" src="https://github.com/williamtroup/Heat.js/assets/18455767/9195fa21-7ca9-4a63-8ab8-9b310972973b">

**Comment by williamtroup** [comment]
Can you post an example of the Vue component please?

Thanks
