### ISSUE TITLE
Display x months (before and after) relative to a set date

### ISSUE THREAD

**Issue by Developarr-Unlimited** [williamtroup/Heat.js#69]
What I would like is to be able to display a 'rolling' heatmap based around a specific date (usually the current date).

There should be a 'buffer' of months shown before/after, e.g. the current month and the previous 3 months and the next 1 month (values should be configurable). For example if the current month is February 2024 it should so

November 2023
December 2023
January 2024
February 2024 (current month)
March 2024

I did try to combine two heatmaps side by side to display Nov/Dec 2023 in one and Jan/Feb/Mar 2024 in another but it's just too much work to get them aligned and looking like a single heatmap.

**Comment by william-troup** [comment]
Hello,

I'm sorry for the delay in replying.  This is not currently supported, as it's meant to be a month-by-month breakdown.  However, enhancements views are coming in v5, which will help with this.

Thanks
